"""add_daily_todo_flags

Revision ID: 220484e0b0d7
Revises: 917a776f9318
Create Date: 2026-06-19 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220484e0b0d7'
down_revision: Union[str, Sequence[str], None] = '917a776f9318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_daily', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('todos', sa.Column('daily_last_reset_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'daily_last_reset_at')
    op.drop_column('todos', 'is_daily')
    # ### end Alembic commands ###
