"""add_food_presets_and_food_logs_tables

Revision ID: 917a776f9318
Revises: 435c9127a418
Create Date: 2026-06-18 11:19:29.464008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917a776f9318'
down_revision: Union[str, Sequence[str], None] = '435c9127a418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'food_presets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('calories_per_100g', sa.Float(), nullable=False),
        sa.Column('protein_per_100g', sa.Float(), nullable=False),
        sa.Column('carbs_per_100g', sa.Float(), nullable=False),
        sa.Column('fat_per_100g', sa.Float(), nullable=False),
        sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_presets_id'), 'food_presets', ['id'], unique=False)
    op.create_index(op.f('ix_food_presets_user_id'), 'food_presets', ['user_id'], unique=False)

    op.create_table(
        'food_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('food_preset_id', sa.Integer(), nullable=True),
        sa.Column('food_name', sa.String(length=100), nullable=False),
        sa.Column('amount_g', sa.Integer(), nullable=False),
        sa.Column('calculated_calories', sa.Float(), nullable=False),
        sa.Column('calculated_protein', sa.Float(), nullable=False),
        sa.Column('calculated_carbs', sa.Float(), nullable=False),
        sa.Column('calculated_fat', sa.Float(), nullable=False),
        sa.Column('logged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['food_preset_id'], ['food_presets.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_logs_id'), 'food_logs', ['id'], unique=False)
    op.create_index(op.f('ix_food_logs_user_id'), 'food_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_logs_user_id'), table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_id'), table_name='food_logs')
    op.drop_table('food_logs')

    op.drop_index(op.f('ix_food_presets_user_id'), table_name='food_presets')
    op.drop_index(op.f('ix_food_presets_id'), table_name='food_presets')
    op.drop_table('food_presets')
    # ### end Alembic commands ###
